### ISSUE TITLE
PX-Dev & Consul: Test connection from KVDB failed

### ISSUE THREAD

**Issue by Berndinox** [portworx/px-dev#18]
**System:**

3 Node Swarm Cluster
Ubuntu 16 .04
Docker 1.13

## Steps performed:

docker network create --driver overlay consul --attachable

**consul.yaml**
```
version: '3'

services:

  consul1:
    image: "progrium/consul:latest"
    hostname: "consul1"
    command: "-server -bootstrap-expect 3 -ui-dir /ui"
    networks:
      - consul

  consul2:
    image: "progrium/consul:latest"
    hostname: "consul2"
    command: "-server -join consul1"
    depends_on:
      - consul1
    networks:
      - consul

  consul3:
    image: "progrium/consul:latest"
    hostname: "consul3"
    command: "-server -join consul1"
    depends_on:
      - consul1
    networks:
      - consul

networks:
  consul:
    external: true
```

`docker stack deploy --compose-file consul.yaml consul`

**config.json:**
```
{
  "clusterid": "5ac2ed6f-7e4e-4e1d-8e8c-3a6df1fb61a5",
  "kvdb": [
              "consul:http://consul1:8500",
              "consul:http://consul2:8500",
              "consul:http://consul3:8500"
         ],
  "storage": {
    "devices": [
      "/dev/vdb"
    ]
  }
}

```

**PX-Dev start:**
```
docker run --restart=always --name px -d --net=consul     \
                 --privileged=true                             \
                 -v /run/docker/plugins:/run/docker/plugins    \
                 -v /var/lib/osd:/var/lib/osd           \
                 -v /dev:/dev                                  \
                 -v /etc/pwx:/etc/pwx                          \
                 -v /opt/pwx/bin:/export_bin            \
                 -v /var/run/docker.sock:/var/run/docker.sock  \
                 -v /var/cores:/var/cores                      \
                 -v /usr/src:/usr/src                          \
                 -v /lib/modules:/lib/modules                  \
                 --ipc=host                                    \
                portworx/px-dev
```

**Verify connectivity:**
```
root@sw1:~# docker exec -it px-dev curl http://consul1:8500
<a href="/ui/">Moved Permanently</a>.
```

When executing pxctl:
```
root@sw1:~# /opt/pwx/bin/pxctl help
WARN[0000] Test connection from KVDB failed: Get http://consul1:8500/v1/kv/pwx/5ac2ed6f-7e4e-4e1d-8e8c-3a6df1fb61a5/testConnection?consistent=: dial tcp: lookup consul1 on 10.1.94.8:53: no such host
WARN[0001] Test connection from KVDB failed: Get http://consul1:8500/v1/kv/pwx/5ac2ed6f-7e4e-4e1d-8e8c-3a6df1fb61a5/testConnection?consistent=: dial tcp: lookup consul1 on 10.1.94.8:53: no such host
Invalid PX Configuration: Configuration check failed: Failed to test connection with KVDB, tried 2
root@sw1:~#
```

**UPDATE:**

After Publishing a Consul Port (_config.json http://127.0.0.1:8500_) and using --net host KVDB connection error disappeard, however i run into a new issue:

```
root@sw1:~# pxctl status
PX is not running on this host
```

logs from px-dev container:
```
time="2017-02-06T12:25:37Z" level=error msg="This node is already initialized but could not be found in the cluster map."
time="2017-02-06T12:25:37Z" level=error msg="Failed to initialize node in cluster. Node is already initialized but not found in the cluster."
time="2017-02-06T12:25:37Z" level=error msg="Could not start cluster manager because of: Node is already initialized but not found in the cluster."
px daemon exited with code: 1

19483
trying to kill px-storage...

2017-02-06 12:25:37,091 INFO exited: pxdaemon (exit status 1; not expected)

```
