### ISSUE TITLE
Document where and how to provide kubernetes credentials

### ISSUE THREAD

**Issue by steigr** [portworx/px-dev#31]
I'm using kubernetes bootstrapped via tectonic-installer with RBAC enabled. I submitted a `kubernetes.yaml`/`admin.conf` likewise:

```
apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    server: https://controller.my-kubenetes.dev:443
    certificate-authority: /etc/kubernetes/ca.crt
preferences:
  colors: true
```

I also volume-mounted a working `kubeconfig` to `/root/.kube/config`. The following error persists:

```
time="2017-05-23T08:59:37Z" level=error msg="Could not initialize scheduler hooks for kubernetes: the server has asked for the client to provide credentials (get nodes)"
```
